name: Build Geode Mod
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android
          build-config: Release
      - name: Upload .geode file
        uses: actions/upload-artifact@v4
        with:
          name: megahackv9-android
          path: build/**/*.geode
